name: Create Jira Ticket

on:
  pull_request:
    types: [opened]

jobs:
  create-ticket:
    runs-on: ubuntu-latest

    steps:
      - name: Create Jira Issue
        run: |
          RESPONSE=$(curl -s -X POST \
            -u "${{ secrets.JIRA_EMAIL }}:${{ secrets.JIRA_API_TOKEN }}" \
            -H "Accept: application/json" \
            -H "Content-Type: application/json" \
            https://${{ secrets.JIRA_SITE }}/rest/api/3/issue \
            --data '{
              "fields": {
                "project": {
                  "key": "KAN"
                },
                "summary": "PR #${{ github.event.pull_request.number }} - ${{ github.event.pull_request.title }}",
                "issuetype": {
                  "name": "Task"
                }
              }
            }')

          echo "$RESPONSE"
